[package]
name = "pore"
version = "0.1.0"
edition = "2021"

readme = "README.md"
license = "MIT"

[dependencies]
anyhow = { version = "1.0.104", features = ["backtrace"] }
atty = "0.2.14"
chrono = { version = "0.4.45", features = ["serde"] }
clap = "4.6.6"
ignore = "0.4.33"
mlua = { version = "0.12.0", features = ["async", "macros", "lua51", "vendored"] }
serde = "1.0.229"
serde_json = "1.0.151"
tantivy = "0.26.1"
termcolor = "1.4.1"
toml = "1.1.4+spec-1.1.0"
macros = { path = "../macros" }
pore-core = { path = "../pore-core" }

[dev-dependencies]
tempfile = "3.27.0"

[[bin]]
name = "pore"
path = "src/main.rs"
